### ISSUE TITLE
Mixin error traced to this mod

### ISSUE THREAD

**Issue by Sunconure11** [Emafire003/FoxGlow#2]
https://pastebin.com/eUPejamT

**Comment by Emafire003** [comment]
Could you please fill me in with some more details like what version of the mod are you using and your minecraft version and such?

**Comment by Sunconure11** [comment]
1.0.3 for the mod, 0.13.1 for the loader, 1.18.1 for the game

**Comment by Emafire003** [comment]
Uh. That's rather strange since it says that there is an error with a non-existing ExampleMixin in the mixin file. Does it happen with an older version? Could you also send me zip of the mods you are using?

**Comment by Sunconure11** [comment]
I'm currently debugging another issue, but... my mod count might hit some kind of limit, though I'll see what I can do.

**Comment by Sunconure11** [comment]
Of note is that I do have a mod installed that has it's own fox variants

**Comment by Sunconure11** [comment]
https://www.curseforge.com/minecraft/mc-mods/shadews-foxes

**Comment by Emafire003** [comment]
Do me a favor and try using this version instead, i may have found the cause https://github.com/Emafire003/FoxGlow/releases/tag/v1.0.4

**Comment by Sunconure11** [comment]
I'll test it after I've found the cause of a bug I'm currently running into that is unrelated to your mod

**Comment by Emafire003** [comment]
Ok, btw this mod currently probably won't work with the mod you linked me for now

**Comment by Emafire003** [comment]
I think it should be fixed now, let me know and i'll close the issue
