### ISSUE TITLE
[Feature request] Option to add more food

### ISSUE THREAD

**Issue by tarkidu** [Emafire003/FoxGlow#4]
I would like to have an option to add the effect to other food like _Glow Berry Cookies_ or _Glowing Juice_ from the [Food+ Mod](https://www.curseforge.com/minecraft/mc-mods/food-pluss).

**Comment by Emafire003** [comment]
Uhm yes could be interesting I will look into it later thanks !

**Comment by Emafire003** [comment]
It took a while, because this project slid pretty low on my todo list, but with the next update any food from any mod will be supported.
